config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :posts do
    resources :answers
  end

  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, :presence => true
  validates :body, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  has_many :posts
  has_many :answers

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/UsersController.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again!"
      redirect_to :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @answer = @post.answers.new
  end

  def create
    if current_user
      @post = Post.find(params[:post_id])
      @answer = @post.answers.new(answer_params)
      @answer.user = current_user
      if @answer.save
         redirect_to post_path(@post)
      else
        render :new
      end
    else
      flash[:alert] = "You must be logged in to reply to a post!"
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @answer = @post.answers.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @answer = @post.answers.find(params[:id])
    if current_user
      if @answer.user_id == current_user.id
        if @answer.update(answer_params)
          redirect_to post_path(@answer.post)
        else
          render :edit
        end
      else
        flash[:alert] = "You cannot edit an answer if you didn't write it"
        redirect_to post_path
      end
    else
      flash[:alert] = "You must be signed in to edit a post"
      redirect_to post_path
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @answer = @post.answers.find(params[:id])

      if current_user
        if @answer.user_id == current_user.id
          @answer.destroy
          redirect_to post_path(@post)
        else
          flash[:alert] = "You cannot delete an answer if you didn't write it"
          redirect_to post_path(@post)
        end
      else
        flash[:alert] = "You must be signed in to delete an answer"
        redirect_to posts_path
      end
  end


  private

  def answer_params
    params.require(:answer).permit(:content)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    if current_user
      @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to post_path(@post)
      else
        render :new
      end
    else
      flash[:alert] = "You must be logged in to create a post!"
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
      if current_user
        if @post.user_id == current_user.id
          if @post.update(post_params)
            redirect_to post_path(@post)
          else
            render :edit
          end
        else
          flash[:alert] = "You Cannot Edit A Post If You Didn't Write It"
          redirect_to post_path
        end
      else
        flash[:alert] = "You must be signed in to edit a post"
        redirect_to posts_path
      end
  end

  def destroy
    @post = Post.find(params[:id])
      if current_user
        if @post.user_id == current_user.id
          @post.destroy
        else
          flash[:alert] = "You Cannot Delete A Post If You Didn't Write It"
          redirect_to post_path
        end
      else
        flash[:alert] = "You must be signed in to edit a post"
        redirect_to posts_path
      end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

      if @user
        flash[:notice] = "You've been logged in #{@user.email}"
        session[:user_id] = @user.id
        redirect_to "/"
      else
        flash[:alert] = "There was a problem logging you in."
        redirect_to log_in_path
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again!"
      redirect_to :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for [@post, @answer ] do |f| %>
<%= f.label "Content" %>
<%= f.text_area "content" %>
<%= f.submit "Answer" %>
<% end %>

app/views/answers/edit.html.erb
<h4>Edit answer for <%= @post.title %> </h4>

<%= render 'form' %>

app/views/answers/new.html.erb
<h1>Reply to <%=@post.title%></h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <ul class="nav navbar-nav navbar-left">
          <% if current_user %>
            <li>Logged in as <%= current_user.email %></li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
           <li><%= link_to "Log Out", log_out_path %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Log in', log_in_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-left">
              <li><%= link_to 'Home', root_path %></li>
          </ul>
        </div>
      </div>
    </nav>


    <%= flash[:notice] %>
    <%= flash[:alert] %>


  <div class="container">
  <%= yield %>

  </body>
  </div>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= f.label "Title" %>
<%= f.text_field "title" %>
<%= f.label "Body" %>
<%= f.text_area "body" %>
<%= f.submit "Create A Post" %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit <%= @post.title %> </h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Stack Yo</h1>
<br>
<% if current_user %>
<%= link_to 'Create Post', new_post_path %>
<% end %>
<br>
<br>
<% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
<% end %>

app/views/posts/new.html.erb
<h2>Create A New Post Yo</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<h5><%= @post.body %></h5>
<% if current_user %>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<%= link_to 'Delete Post', post_path(@post),
                            :data => {:confirm => "Ya sure mate?",
                            :method => "delete"} %>
<% end %>

<%= link_to "Answer Post", new_post_answer_path(@post, @user) %>


<% if @post.answers.any? %>
  <h4>Answers</h4>
    <% @post.answers.each do |answer| %>
      <li><%=answer.created_at %> <%= answer.user.email %> says:
      <%= answer.content %></li>
        <% if current_user %>

        <%= link_to 'Edit Answer', edit_post_answer_path(@post, answer) %>
        <%= link_to 'Delete Answer', post_answer_path(@post, answer),
                              :data => {:confirm => "Ya sure mate?",
                              :method => "delete"} %>




        <% end %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<h1>Sign Up</h1>

<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<%=render 'form' %>